CREATE TABLE [dbo].[Videos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[VideoProvider] [varchar](512) NOT NULL,
	[VideoProviderKey] [varchar](512) NOT NULL,
	[Title] [varchar](512) NOT NULL,
	[CreatedByUserId] [int] NOT NULL,
	[CreatedAt] [datetime] NOT NULL
 CONSTRAINT [PK_Videos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[TimeCodes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[VideoId] [int] NOT NULL,
	[TimeCodeType] [varchar](128) NOT NULL,
	[Name] [varchar](128) NULL,
	[StartMs] [int] NOT NULL,
	[EndMs] [int] NOT NULL,
	[Index] [int] NOT NULL
 CONSTRAINT [PK_TimeCodes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[Fundamentals](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Code] [varchar](128) NOT NULL,
	[Text] [varchar](512) NOT NULL,
	[Index] [int] NOT NULL
 CONSTRAINT [PK_Fundamentals] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[SkiPerformances](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Code] [varchar](128) NOT NULL,
	[Text] [varchar](512) NOT NULL,
	[Index] [int] NOT NULL
 CONSTRAINT [PK_SkiPerformances] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[TurnPhases](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Code] [varchar](128) NOT NULL,
	[Text] [varchar](512) NOT NULL,
	[Index] [int] NOT NULL
 CONSTRAINT [PK_TurnPhases] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[Causes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Code] [varchar](128) NOT NULL,
	[Text] [varchar](512) NOT NULL,
	[Index] [int] NOT NULL,
	[FundamentalId] [int] NOT NULL
 CONSTRAINT [PK_Causes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[Effects](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Code] [varchar](128) NOT NULL,
	[Text] [varchar](512) NOT NULL,
	[Index] [int] NOT NULL,
	[SkiPerformanceId] [int] NOT NULL,
 CONSTRAINT [PK_Effects] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[EffectTurnPhases](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[EffectId] [int] NOT NULL,
	[TurnPhaseId] [int] NOT NULL,
 CONSTRAINT [PK_EffectTurnPhases] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[EffectCauses](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[EffectId] [int] NOT NULL,
	[CauseId] [int] NOT NULL,
 CONSTRAINT [PK_EffectPhases] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[TurnShapes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Code] [varchar](128) NOT NULL,
	[Text] [varchar](512) NOT NULL,
	[Index] [int] NOT NULL
 CONSTRAINT [PK_TurnShapes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[TurnShapeCauses](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TurnShapeId] [int] NOT NULL,
	[CauseId] [int] NOT NULL,
 CONSTRAINT [PK_TurnShapeCauses] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[BodyIndications](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Code] [varchar](128) NOT NULL,
	[Text] [varchar](512) NOT NULL,
	[Index] [int] NOT NULL
 CONSTRAINT [PK_BodyIndications] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[BodyIndicationCauses](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[BodyIndicationId] [int] NOT NULL,
	[CauseId] [int] NOT NULL,
 CONSTRAINT [PK_BodyIndicationCauses] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]